// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKtdyEcEtkquKikBne6VA2bpG29Rkzsk',
    appId: '1:468158010545:web:83937933e0c94d8413be90',
    messagingSenderId: '468158010545',
    projectId: 'flutter-chat-a6c95',
    authDomain: 'flutter-chat-a6c95.firebaseapp.com',
    storageBucket: 'flutter-chat-a6c95.appspot.com',
    measurementId: 'G-TWQ555552M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jb7ynF5ZOhHCU9ayPhtMUV7RfGp1oG4',
    appId: '1:468158010545:android:68dafa651ecf87bd13be90',
    messagingSenderId: '468158010545',
    projectId: 'flutter-chat-a6c95',
    storageBucket: 'flutter-chat-a6c95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGM8PORYV9XXSy9H-OikQC6938kdYPcEI',
    appId: '1:468158010545:ios:32ccfb8aa02f2bb413be90',
    messagingSenderId: '468158010545',
    projectId: 'flutter-chat-a6c95',
    storageBucket: 'flutter-chat-a6c95.appspot.com',
    iosBundleId: 'com.example.techMedia',
  );
}
